# FROM node:20.16.0-alpine3.20

# # Install dependencies
# RUN apk add --no-cache redis

# # Set the working directory
# WORKDIR /app

# # Copy package.json and package-lock.json
# COPY package.json package-lock.json ./

# # Install Node.js dependencies
# RUN npm ci

# # Copy the rest of the application code
# COPY . .


# # Build the application
# RUN npm run build

# # Expose the ports for Node.js app and Redis
# EXPOSE 5001 6379

# # Copy the start script
# COPY start.sh /start.sh
# RUN chmod +x /start.sh

# # Use the start script as the entry point
# CMD ["/start.sh"]


FROM node:20.16.0-alpine3.20

# Install dependencies
RUN apk add --no-cache redis openjdk11-jre bash

# Install Kafka
# ENV KAFKA_VERSION=3.8.0
# ENV SCALA_VERSION=2.13
# RUN wget https://downloads.apache.org/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz \
#     && tar -xzf kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz \
#     && mv kafka_${SCALA_VERSION}-${KAFKA_VERSION} /kafka \
#     && rm kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install Node.js dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .


# Define build arguments
ARG NODE_ENV
ARG CLIENT_URL
ARG ADMIN_URL
ARG JWT_USER_SECRET
ARG JWT_ADMIN_SECRET
ARG BASE_URL
ARG REDIS_HOST
ARG REDIS_PORT
ARG PORT_DEV
ARG DB_URL_DEV
ARG PORT_PROD
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG PORT_TEST
ARG DB_URL_TEST
ARG STRIPE_SECRET_KEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CALLBACK_URL
ARG CLAUDE_SECRET
ARG CLAUDE_MODEL
ARG CLAUDE_MAX_TOKENS
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG SUMSUB_SECRET_KEY
ARG SUMSUB_APP_TOKEN
ARG SUMSUB_LEVEL_NAME
ARG RAPIDAPI_KEY
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USER
ARG MAIL_PASS
ARG OPENAI_API_KEY
ARG ACTIVE_AI_MODEL
ARG HUGGINGFACE_API_KEY
ARG PINATA_API_KEY
ARG PINATA_API_SECRET
ARG PINATA_JWT
ARG PINATA_GATEWAY_KEY
ARG FILEBASE_ACCESS_KEY_ID
ARG FILEBASE_SECRET_ACCESS_KEY
ARG FILEBASE_BUCKET_NAME
ARG FILEBASE_REGION
ARG TELEGRAM_BOT_TOKEN
ARG TELEGRAM_CHAT_ID
ARG PROD_ADMIN_ADDRESS
ARG DEV_ADMIN_ADDRESS
ARG TELEGRAM_GROUP_USERNAME


# Pass the build arguments as environment variables
ENV NODE_ENV=$NODE_ENV \
    CLIENT_URL=$CLIENT_URL \
    ADMIN_URL=$ADMIN_URL \
    JWT_USER_SECRET=$JWT_USER_SECRET \
    JWT_ADMIN_SECRET=$JWT_ADMIN_SECRET \
    BASE_URL=$BASE_URL \
    REDIS_HOST=$REDIS_HOST \
    REDIS_PORT=$REDIS_PORT \
    PORT_DEV=$PORT_DEV \
    DB_URL_DEV=$DB_URL_DEV \
    PORT_PROD=$PORT_PROD \
    DB_NAME=$DB_NAME \
    DB_USER=$DB_USER \
    DB_PASSWORD=$DB_PASSWORD \
    DB_HOST=$DB_HOST \
    PORT_TEST=$PORT_TEST \
    DB_URL_TEST=$DB_URL_TEST \
    STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY \
    GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
    GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
    GOOGLE_CALLBACK_URL=$GOOGLE_CALLBACK_URL \
    CLAUDE_SECRET=$CLAUDE_SECRET \
    CLAUDE_MODEL=$CLAUDE_MODEL \
    CLAUDE_MAX_TOKENS=$CLAUDE_MAX_TOKENS \
    CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME \
    CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
    CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET \
    SUMSUB_SECRET_KEY=$SUMSUB_SECRET_KEY \
    SUMSUB_APP_TOKEN=$SUMSUB_APP_TOKEN \
    SUMSUB_LEVEL_NAME=$SUMSUB_LEVEL_NAME \
    RAPIDAPI_KEY=$RAPIDAPI_KEY \
    MAIL_HOST=$MAIL_HOST \
    MAIL_PORT=$MAIL_PORT \
    MAIL_USER=$MAIL_USER \
    MAIL_PASS=$MAIL_PASS \
    OPENAI_API_KEY=$OPENAI_API_KEY \
    ACTIVE_AI_MODEL=$ACTIVE_AI_MODEL \
    HUGGINGFACE_API_KEY=$HUGGINGFACE_API_KEY \
    PINATA_API_KEY=$PINATA_API_KEY \
    PINATA_API_SECRET=$PINATA_API_SECRET \
    PINATA_JWT=$PINATA_JWT \
    PINATA_GATEWAY_KEY=$PINATA_GATEWAY_KEY \
    FILEBASE_ACCESS_KEY_ID=$FILEBASE_ACCESS_KEY_ID \
    FILEBASE_SECRET_ACCESS_KEY=$FILEBASE_SECRET_ACCESS_KEY \
    FILEBASE_BUCKET_NAME=$FILEBASE_BUCKET_NAME \
    FILEBASE_REGION=$FILEBASE_REGION \
    TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
    TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID \
    PROD_ADMIN_ADDRESS=$PROD_ADMIN_ADDRESS \
    DEV_ADMIN_ADDRESS=$DEV_ADMIN_ADDRESS \
    TELEGRAM_GROUP_USERNAME=$TELEGRAM_GROUP_USERNAME

# Build the application
RUN npm run build

# Expose the ports for Node.js app, Redis, and Kafka
EXPOSE 5001 6379 9092

# Copy the start script
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Use the start script as the entry point
CMD ["/start.sh"]
