export interface ILaunchCollection {
  _id?: string;
  user: string;
  collectionName: string;
  creatorName: string;
  creatorWallet: string;
  creatorEmail: string;
  projectDescription: string;
  projectCategory: string;
  expectedLaunchDate: string;
  twitter: string;
  discord: string;
  instagram: string;
  website: string;
  totalSupply: string;
  contractType: string;
  royaltyPercentage: string;
  mintPrice: string;
  mintPriceCurrency: string;
  tokenList: string[];
  policy: string[];
  collectionCoverImage: string;
  collectionBannerImage: string;
  mintStartDate: string;
  mintStartTime: string;
  allowFreeMints: boolean;
  enableWhitelist: boolean;
  enablePresale: boolean;
  enableAirdrop : boolean;
  isPaid: boolean;
  paymentMode: string;
  transactionId: string;
  isApproved: boolean;
  isRejected: boolean;
  createdAt: Date;
  updatedAt: Date;
}
