import { ICollection } from "../../interfaces/collection/collection.interface";

export const collectionResponseData = (collection: ICollection) => {
  return {
    _id: collection._id,
    user: collection.user,
    applicationId: collection.applicationId,
    applicationType: collection.applicationType,
    collectionName: collection.collectionName,
    slug: collection.slug,
    tokenSymbol: collection.tokenSymbol,
    collectionInfo: collection.collectionInfo,
    collectionUrl: collection.collectionUrl,
    category: collection.category,
    imageUrl: collection.imageUrl,
    bannerUrl: collection.bannerUrl,
    totalSupply: collection.totalSupply,
    mintPrice: collection.mintPrice,
    isActive: collection.isActive,
    tokenList: collection.tokenList,
    royaltyFee: collection.royaltyFee,
    royaltyAddress: collection.royaltyAddress,
    totalNftPrice: collection.totalNftPrice,
    totalNft: collection.totalNft,
    minNftPrice: collection.minNftPrice,
    maxNftPrice: collection.maxNftPrice,
    totalNftUser: collection.totalNftUser,
    createdAt: collection.createdAt,
    updatedAt: collection.updatedAt,
    collectionId: collection.collectionId,
    size: collection.size,
    maxSize: collection.maxSize,
    creator: collection.creator,
    creatorGuard: collection.creatorGuard,
    tokens: collection.tokens,
    firstTokenData: collection.firstTokenData,
    lastUpdated: collection.lastUpdated,
    collectionCoverImage: collection.collectionCoverImage,
    collectionBannerImage: collection.collectionBannerImage,
    reservePrice: collection.reservePrice,
  };
};
