import express from "express";
import adminRouter from "./routes/admin.route";
import blogRouter from "./routes/blog.route";
import cartRouter from "./routes/cart.route";
import claudeRouter from "./routes/claude.route";
import collectionRouter from "./routes/collection.route";
import configRouter from "./routes/config.route";
import launchCollectionRouter from "./routes/launch-collection.route";
import nftRouter from "./routes/nft.route";
import transactionRouter from "./routes/transactions.route";
import userRouter from "./routes/user.route";
import userPointsRouter from "./routes/userpoints.route";
import verificationRouter from "./routes/verification.route";
import superAdminRouter from "./routes/superadmin.route";
import elasticRouter from "./routes/elastic.route";
import singleNftRouter from "./routes/singleNft.route";
import activityRouter from "./routes/activity.route";
import stageApplicationRouter from "./routes/stage-application.routes";
import musicRouter from "./routes/music.routes";

const router = express.Router();

router.use("/admin", adminRouter);
router.use("/user", userRouter);
router.use("/cart", cartRouter);
router.use("/transaction", transactionRouter);
router.use("/collection", collectionRouter);
router.use("/nft", nftRouter);
router.use("/single-nft", singleNftRouter);
router.use("/config", configRouter);
router.use("/userpoints", userPointsRouter);
router.use("/claude", claudeRouter);
router.use("/verification", verificationRouter);
router.use("/launch-collection", launchCollectionRouter);
router.use("/blog", blogRouter);
router.use("/superadmin", superAdminRouter);
router.use("/elastic", elasticRouter);
router.use("/activity", activityRouter);
router.use("/stage-application", stageApplicationRouter);
router.use("/music", musicRouter);

export default router;
