name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20' 
      - name: Install dependencies
        run: yarn install
      - name: SonarQube Scan
        # uses: SonarSource/sonarqube-scan-action@master
        uses: SonarSource/sonarcloud-github-action@master
        # env:
        #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=rahulb15
            -Dsonar.projectKey=rahulb15_K-Backend-New